### ISSUE TITLE
Please update the bot! (its outdated and doesnt work when install)

### ISSUE THREAD

**Issue by Arkaeologist** [sblaplace/DiscordPointBot#9]
Doesnt work when installing...

**Comment by sblaplace** [comment]
I do not currently have the time to update this project, however, I will happily review any pull requests that are sent my way. Apologies in advance for any inconvenience this causes you.

**Comment by Arkaeologist** [comment]
Thanks but do you know of any other bots that just lets you award points and nothing else? It will be great for running events.

**Comment by Arkaeologist** [comment]
Hello, if you don't know of any. Do you think you will be updating the bot anytime soon?
